language: ruby
rvm: 2.3.3
sudo: required
services:
  - docker
install:
  - gem install github-pages -v 108
script:
  - make docs &&
    make docker-gram-build &&
    make docker-gram &&
    docker run gramlang/gram gram -v && (
      test "$TRAVIS_PULL_REQUEST" != "false" ||
      test "$TRAVIS_BRANCH" != "master" || (
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
        docker push gramlang/gram:latest
      )
    )
