language: generic
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
install:
  - make install-deps
  - make install-lint-deps
script:
  - make && make lint && sudo make install
