language: generic
services:
  - docker
script:
  - (
      test "$TRAVIS_PULL_REQUEST" != "false" ||
      test "$TRAVIS_BRANCH" != "master" ||
      make docker-gram-deps
    ) &&
    make docker-gram-build &&
    make docker-gram &&
    docker run gramlang/gram gram -v && (
      test "$TRAVIS_PULL_REQUEST" != "false" ||
      test "$TRAVIS_BRANCH" != "master" || (
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
        docker push gramlang/gram:deps &&
        docker push gramlang/gram:build &&
        docker push gramlang/gram:latest
      )
    )
