language: generic
matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      osx_image: xcode7.3
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install cmake; fi
script:
  - sudo make install-deps
  - make
  - sudo make install
