language: generic
sudo: required
services:
  - docker
script:
  - make docker-gram-build && make docker-gram
after_success:
  - docker run gramlang/gram gram -v
  - test "$TRAVIS_PULL_REQUEST" = "false" &&
    test "$TRAVIS_BRANCH" = "master" &&
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
    docker push gramlang/gram:latest ||
    true
