[package]
name = "gram"
version = "0.0.1"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"
description = "A high-level programming language."
license = "MIT"
documentation = "https://github.com/gramlang/gram"
homepage = "https://github.com/gramlang/gram"
repository = "https://github.com/gramlang/gram"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.clap]
version = "2"
features = ["wrap_help"]
