[package]
name = "gram"
version = "0.0.0"
authors = ["Stephan Boyer <stephan@stephanboyer.com>"]
edition = "2018"
description = "A programming language for distributed systems."
license = "MIT"
documentation = "https://github.com/gramlang/gram"
homepage = "https://github.com/gramlang/gram"
repository = "https://github.com/gramlang/gram"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
colored = "1"
num-bigint = "0.2"
pad = "0.1"
scopeguard = "1.0"

[dependencies.clap]
version = "2"
features = ["wrap_help"]
