FROM gramlang/gram:deps
COPY . /root/gram
RUN cd /root && \

  # Speed up the build by using pre-compiled LLVM artifacts.
  cd gram && \
  rm -rf build && \
  mv ../build build && \
  touch build/release/llvm && \

  # Build and lint Gram.
  make lint && \
  make docs && \
  make spec && \
  make
