FROM gramlang/gram:deps
COPY . /root/gram
RUN cd /root && \

  # Speed up the build by using pre-compiled LLVM artifacts.
  cd gram && \
  rm -rf build && \
  mv ../build build && \
  touch build/release/llvm && \

  # Build and lint Gram. We run `make docs` in a login shell (bash -l) because
  # the Ruby installation only works in login shells. This is due to RVM.
  make lint && \
  bash -l -c 'make docs' && \
  make
