FROM debian:jessie
COPY . /root/gram
RUN cd /root && \

  # Sid (unstable) is needed for the `clang-4.0` package.
  echo 'deb http://deb.debian.org/debian sid main' >> \
    /etc/apt/sources.list && \

  # Update package lists.
  DEBIAN_FRONTEND=noninteractive apt-get -y update && \

  # Install various packages.
  # `ruby2.3`, `ruby2.3-dev`, and `zlib1g-dev` are needed for the
  # `github-pages` gem (installed below). `texlive-full` is needed
  # for building the formal specification. `python-pip` is needed
  # to install the AWS CLI (installed below). `groff` is also
  # needed for the AWS CLI.
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
  build-essential \
  clang-4.0 \
  cmake>=3.7.1-1 \
  git \
  groff \
  ninja-build \
  python-pip \
  ruby2.3 \
  ruby2.3-dev \
  shellcheck \
  texlive-full \
  zlib1g-dev && \
  rm -rf /var/lib/apt/lists/* && \
  update-alternatives --install /usr/bin/clang clang \
    /usr/bin/clang-4.0 100 && \
  update-alternatives --install /usr/bin/clang++ clang++ \
    /usr/bin/clang++-4.0 100 && \
  update-alternatives --install /usr/bin/scan-build scan-build \
    /usr/bin/scan-build-4.0 100 && \

  # Install the `github-pages` gem (for `make docs`).
  gem install github-pages -v 111 && \

  # Install the AWS CLI (for `make spec`).
  pip install awscli \

  # Build LLVM for Gram.
  cd gram && \
  make build/release/llvm && \
  cd .. && \
  mv gram/build build && \
  rm -rf gram
